/*
 * Generated by JasperReports - 12/22/05 12:00 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class HW_PO extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillField field_SID = null;
    private JRFillField field_DeliveryAt = null;
    private JRFillField field_Item = null;
    private JRFillField field_Date = null;
    private JRFillField field_Deliver32By = null;
    private JRFillField field_Total = null;
    private JRFillField field_Phone = null;
    private JRFillField field_Email = null;
    private JRFillField field_Price = null;
    private JRFillField field_Dated = null;
    private JRFillField field_Supplier = null;
    private JRFillField field_Mobile = null;
    private JRFillField field_Fax = null;
    private JRFillField field_ContactPerson = null;
    private JRFillField field_Address = null;
    private JRFillField field_Quantity = null;
    private JRFillField field_PO = null;
    private JRFillField field_OfferNo = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_test = null;
    private JRFillVariable variable_total_qty = null;
    private JRFillVariable variable_total_price = null;
    private JRFillVariable variable_total_total = null;
    private JRFillVariable variable_PO_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_SID = (JRFillField)fm.get("SID");
        field_DeliveryAt = (JRFillField)fm.get("DeliveryAt");
        field_Item = (JRFillField)fm.get("Item");
        field_Date = (JRFillField)fm.get("Date");
        field_Deliver32By = (JRFillField)fm.get("Deliver By");
        field_Total = (JRFillField)fm.get("Total");
        field_Phone = (JRFillField)fm.get("Phone");
        field_Email = (JRFillField)fm.get("Email");
        field_Price = (JRFillField)fm.get("Price");
        field_Dated = (JRFillField)fm.get("Dated");
        field_Supplier = (JRFillField)fm.get("Supplier");
        field_Mobile = (JRFillField)fm.get("Mobile");
        field_Fax = (JRFillField)fm.get("Fax");
        field_ContactPerson = (JRFillField)fm.get("ContactPerson");
        field_Address = (JRFillField)fm.get("Address");
        field_Quantity = (JRFillField)fm.get("Quantity");
        field_PO = (JRFillField)fm.get("PO");
        field_OfferNo = (JRFillField)fm.get("OfferNo");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_test = (JRFillVariable)vm.get("test");
        variable_total_qty = (JRFillVariable)vm.get("total_qty");
        variable_total_price = (JRFillVariable)vm.get("total_price");
        variable_total_total = (JRFillVariable)vm.get("total_total");
        variable_PO_COUNT = (JRFillVariable)vm.get("PO_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)("test");
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)("test");
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Quantity.getValue()));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Price.getValue()));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Total.getValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_PO.getValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_total_qty.getValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_total_price.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_total_total.getValue()));
                break;
            }
            case 19 : 
            {
                value = (java.util.Date)(((java.util.Date)field_Deliver32By.getValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DeliveryAt.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)("C:\\Documents and Settings\\AdEeL\\Desktop\\iReportDemoCalling\\Reports\\logo.jpg");
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)field_PO.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.util.Date)(((java.util.Date)field_Date.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_SID.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)field_OfferNo.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.util.Date)(((java.util.Date)field_Dated.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Supplier.getValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Address.getValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Email.getValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Phone.getValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Fax.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Mobile.getValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ContactPerson.getValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Item.getValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Quantity.getValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Price.getValue()));
                break;
            }
            case 37 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Total.getValue()));
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " of ");
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 40 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)("test");
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)("test");
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Quantity.getOldValue()));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Price.getOldValue()));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Total.getOldValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_PO.getOldValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_total_qty.getOldValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_total_price.getOldValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_total_total.getOldValue()));
                break;
            }
            case 19 : 
            {
                value = (java.util.Date)(((java.util.Date)field_Deliver32By.getOldValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DeliveryAt.getOldValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)("C:\\Documents and Settings\\AdEeL\\Desktop\\iReportDemoCalling\\Reports\\logo.jpg");
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)field_PO.getOldValue()));
                break;
            }
            case 23 : 
            {
                value = (java.util.Date)(((java.util.Date)field_Date.getOldValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_SID.getOldValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)field_OfferNo.getOldValue()));
                break;
            }
            case 26 : 
            {
                value = (java.util.Date)(((java.util.Date)field_Dated.getOldValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Supplier.getOldValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Address.getOldValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Email.getOldValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Phone.getOldValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Fax.getOldValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Mobile.getOldValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ContactPerson.getOldValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Item.getOldValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Quantity.getOldValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Price.getOldValue()));
                break;
            }
            case 37 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Total.getOldValue()));
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " of ");
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 40 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)("test");
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)("test");
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Quantity.getValue()));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Price.getValue()));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Total.getValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_PO.getValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_total_qty.getEstimatedValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_total_price.getEstimatedValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_total_total.getEstimatedValue()));
                break;
            }
            case 19 : 
            {
                value = (java.util.Date)(((java.util.Date)field_Deliver32By.getValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DeliveryAt.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)("C:\\Documents and Settings\\AdEeL\\Desktop\\iReportDemoCalling\\Reports\\logo.jpg");
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)field_PO.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.util.Date)(((java.util.Date)field_Date.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_SID.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)field_OfferNo.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.util.Date)(((java.util.Date)field_Dated.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Supplier.getValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Address.getValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Email.getValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Phone.getValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Fax.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Mobile.getValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ContactPerson.getValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)(((java.lang.String)field_Item.getValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Quantity.getValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Price.getValue()));
                break;
            }
            case 37 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_Total.getValue()));
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " of ");
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 40 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
