// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000050-2)
Ads_Build='00000050-2';var QQbA,QQcA,QQdA,QQeA,QQfA,QQgA,QQhA,QQiA,QQjA,QQkA,QQlA,QQmA,QQnA,QQoA,QQpA;NUM_FARM=1;QQbA=['http://a.as-test.falkag.net' ,'http://a.as-eu.falkag.net' ,'http://a.ads.t-online.de' ,'http://a.as-us.falkag.net' ,'','','','','',''];QQcA=['http://a.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'','','','','',''];QQdA=['http://a.as-test.falkag.net' ,'http://a.as-eu.falkag.net' ,'http://a.ads.t-online.de' ,'http://a.as-us.falkag.net' ,'','','','','',''];QQeA=['http://a.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'','','','','',''];QQfA=['http://bw.as-test.falkag.net' ,'http://bw.as-eu.falkag.net' ,'http://bw.ads.t-online.de' ,'http://bw.as-us.falkag.net' ,'','','','','',''];QQgA=['http://bw.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'','','','','',''];QQhA=['http://red.as-test.falkag.net' ,'http://red.as-eu.falkag.net' ,'http://red.ads.t-online.de' ,'http://red.as-us.falkag.net' ,'','','','','',''];QQiA=['http://red.as-test.falkag.net' ,'https://red.as-eu.falkag.net' ,'https://red.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'','','','','',''];QQjA=['http://sel.as-test.falkag.net/server/asldata.js','http://data.as-eu.falkag.net/server/asldata.js','http://data.ads.t-online.de/server/asldata.js' ,'http://sel.as-us.falkag.net/server/asldata.js' ,'','','','','',''];QQkA=['http://sel.as-test.falkag.net/server/asldata.js','https://as1.falkag.de/server/asldata.js' ,'https://red.ads.t-online.de/server/asldata.js' ,'https://s.as-us.falkag.net/server/asldata.js','','','','','',''];QQlA=['.as-test.falkag.net' ,'.as-eu.falkag.net' ,'.ads.t-online.de' ,'.as-us.falkag.net' ,'','','','','',''];QQmA=['Falk AdSolution' ,'AdSolution' ,'Adsolution' ,'Falk AdSolution' ,'','','','','',''];QQnA=['/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'','','','','',''];QQoA=['/red?cmd=red&' ,'/red?cmd=red&' ,'/red?cmd=red&' ,'/red?cmd=red&' ,'','','','','',''];QQpA=['/red?cmd=url&' ,'/red?cmd=url&' ,'/red?cmd=url&' ,'/red?cmd=url&' ,'','','','','',''];// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000050-2)
function QQaD(QQRb)
{document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+QQRb+'"></scr'+'ipt>');}function QQbD(QQSb)
{var QQTb=this.location.hostname.toLowerCase();var QQUb='';var QQVb=QQTb;var QQWb=[];intPos1=QQTb.indexOf('.');if (QQSb==1)
{if (intPos1!=-1)
{while (intPos1!=-1)
{intPos1=QQVb.indexOf('.');QQWb[QQWb.length]=(intPos1==-1)?QQVb.substring(intPos1+1,QQVb.length):QQVb.substring(0,intPos1);QQVb=QQVb.substring(intPos1+1,QQVb.length);}if (QQWb[QQWb.length-2]=='falkag')
{for (var intI=1;intI<QQWb.length;intI++)
{QQl=QQWb.length-intI;QQUb=QQWb[QQl]+((QQUb=='')?'':'.'+QQUb);}}else
{QQUb=(QQWb[QQWb.length-2].length<3)?QQTb:QQWb[QQWb.length-2]+'.'+QQWb[QQWb.length-1];}}}else
{if (intPos1==-1)
{QQUb='';}else
{if((intPos1>=0)&&(intPos1<QQTb.length))
{intPos2=QQTb.indexOf('.',intPos1+1);if(intPos2>intPos1)
QQUb=QQTb.substring(intPos1+1,QQTb.length);}if ((QQUb.lastIndexOf('.')==QQUb.indexOf('.'))&&QQUb.lastIndexOf('.')<3)
QQUb=QQTb;}}return QQUb;}function QQcD()
{var QQUb=QQbD(0);if(QQUb=='')
return 'D'+this.location.hostname;else
return 'D'+QQUb;}function QQdD(QQXb)
{var QQUb=QQbD(0);if(QQXb==-1)
{	 if(QQUb!='')
	 QQUb=' domain='+QQUb;	return ';path=/;'+QQUb;}var QQYb=new Date();if(QQUb!='')
QQUb=';domain='+QQUb;QQYb.setTime(parseInt(QQYb.getTime(),10)+1000*60*parseInt(QQXb,10));return ';path=/;expires='+QQYb.toGMTString()+QQUb;}function QQeD(QQXb)
{var QQUb=QQbD(1);if(QQXb==-1)
{	 if(QQUb!='')
	 QQUb=' domain='+QQUb;	return ';path=/;'+QQUb;}var QQYb=new Date();if(QQUb!='')
QQUb=';domain='+QQUb;QQYb.setTime(parseInt(QQYb.getTime(),10)+1000*60*parseInt(QQXb,10));return ';path=/;expires='+QQYb.toGMTString()+QQUb;}function QQfD(QQc,QQd,QQy)
{if(QQsA!=-1) var intBwdTyp=KAS[QQsA][4][27];if(typeof(intBwdTyp)=='undefined')
intBwdTyp=0;var QQz=[];QQoD(1,'InternData',(QQxC( Ads_iid,QQc )&&(QQuB>0))?QQtB:'');QQz[0]='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd+'&kid='+QQc+QQy[0]+((QQxC( Ads_iid,QQc )&&(QQuB>0))?QQtB:'');QQz[1]='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd+'&kid='+QQc+'&chw='+QQqA+'&tcs='+QQrA+QQy[1]+((QQxC( Ads_iid,QQc )&&(QQuB>0))?QQtB:'')+QQvA;var QQZb='&sta=';QQz[0]+='&dmn='+Ads_T[5];QQz[1]+='&dmn='+Ads_T[5];if(navigator.appVersion.substring(0,1)>'3')
{QQz[0]+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;QQz[1]+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;QQZb+=',,,'+(navigator.javaEnabled()?'1':'0');if(navigator.javaEnabled())
QQz[1]+='&jav=1';}else
QQZb+=',,,';var QQAc=new Date();QQZb+=',,,,,,';if((Ads_wrd!='')&&(Ads_wrd.toLowerCase()!='[keyword]'))
{var QQBc='!"%&\'()*+#-./:;<=>?@[\\]^{|}~§ ';var QQCc,QQDc='';for(QQl=0;QQl<Ads_wrd.length;QQl++)
{QQCc=Ads_wrd.charAt(QQl);if(QQBc.indexOf(QQCc)!=-1)
QQCc=',';QQDc+=QQCc;}QQDc =QQDc.toLowerCase();QQz[0]+='&wrd='+QQDc;QQz[1]+='&wrd='+QQDc;Ads_wrd=QQDc;QQZb+='';}QQZb+=','+QQvE[10]+','+Ads_T[13]+','+intBwdTyp+','+Ads_T[4]+','+Ads_T[10]+','+Ads_T[11]+','+Ads_T[3]+','+Ads_T[12];QQz[0]+=QQZb;QQz[1]+=QQZb;if(gbolSUXX25067) QQz[1]+='&trglog='+escape(gstrXarrTargetDaten);QQz[0]=Ads_Timestamp+QQz[0];QQz[1]=Ads_Timestamp+QQz[1];QQz[2]=QQz[1]+QQy[0];return (QQz);}function QQgD(QQc,QQd,QQy)
{var QQEc=[];var QQFc=[];QQFc=QQfD(QQc,QQd,QQy);QQEc[0] ='&rdm='+QQFc[0]+'&iid='+Ads_iid+'&bid='+QQd;QQEc[1] ='&rdm='+QQFc[1]+'&iid='+Ads_iid+'&bid='+QQd;return QQEc;}function QQhD()
{if (typeof(QQgB[Ads_sec])=='undefined')
QQtC();return QQgB[Ads_sec]+(QQyA?QQoA[NUM_FARM]+'flg='+QQwC()+'&dat='+QQfB[Ads_sec]+'/dat/bgf/trpix.gif&':QQnA[NUM_FARM]);}function QQiD()
{return QQgB[Ads_sec]+QQnA[NUM_FARM]+'cmd=req&';}function QQjD(QQGc,QQb)
{if (QQGc==0)
{QQoD(1,'',QQhD()+QQb);return ((Ads_opt&512)>0)?'':(QQsD('Ads_Count'+Ads_iid)+'<img src="'+QQhD()+QQb+'" width="1" height="1">'+QQtD());}else if (QQGc==1)
{QQoD(1,'Request tracking URL',QQiD()+QQb);return QQsD('Ads_ReqCount'+Ads_iid)+'<img src="'+QQiD()+QQb+'" width="1" height="1">'+QQtD();}}function QQkD(QQt,QQb)
{QQt.document.write(QQjD(0,QQb));}function QQlD()
{return QQmD(Math.random()*100000000,8);}function QQmD(QQHc,QQIc)
{var QQJc='#'+(QQHc+100000000);return QQJc.substr(10-QQIc,QQIc);}function QQnD(QQDc,QQKc,QQLc)
{var QQl;while((QQl=QQDc.indexOf(QQKc))!=-1)
QQDc=QQDc.substr(0,QQl)+QQLc+QQDc.substring(QQl+QQKc.length,QQDc.length);return QQDc;}function QQoD(QQD,QQDc,QQMc)
{var QQNc=new Date();if(Ads_debug==1)
{document.write(((QQD!=3)?'':'<br>')+'<font color=#0000ff>[DEBUG'+((QQNc-QQwA)/1000)+']</font> ');if((QQD==0)||(QQD==3))
document.write('<b><big>'+QQDc+'</big></b><br>');else if(QQD==1)
document.write(''+QQDc+': &nbsp;<font color=#000080>'+QQMc+'</font><br>');else
document.write('<b>'+QQDc+'</b><br>');}else if((Ads_debug==2)&&(QQD==3))
document.write('<font color=#0000ff>[DEBUG'+((QQNc-QQwA)/1000)+']</font> <b><big>'+QQDc+'</big></b><br>');}function QQpD(QQAb)
{var QQC='#'+(parseInt(QQAb,10)+100000000);return QQC.substr(2,2)+'/'+QQC.substr(4,2)+'/'+QQC.substr(6,2)+'/'+QQC.substr(8,2);}function QQqD(QQHc)
{var QQOc='0123456789ABCDEF';var QQPc='';while(QQHc>0)
{QQPc=QQOc.substr(QQHc%16,1)+QQPc;QQHc=parseInt(QQHc/16,10);}return (QQPc=='')?'0':QQPc;}function QQrD(QQKa)
{var QQQc;var QQRc=0;if(QQaB>-1)
{QQRc=QQaB;return QQRc;}if((QQKa==0)&&((Ads_opt&2048)>0))
return -1;if((navigator.userAgent.indexOf("Opera")!=-1)||((navigator.appName=="Netscape")&&(navigator.userAgent.indexOf("Mozilla")!=-1)&&(parseFloat(navigator.appVersion)>=4)))
{if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)
{QQQc=navigator.plugins['Shockwave Flash'].description;QQQc=QQQc.substring(QQQc.indexOf("."),-1);QQRc=QQQc.substr(-1);}}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Mac")!=-1&&document.all)
{if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)
{QQQc=navigator.plugins['Shockwave Flash'].description;QQQc=QQQc.substring(QQQc.indexOf("."),-1);QQQc=QQQc.substring(QQQc.length-1,QQQc.length);QQRc=QQQc.substr(-1);}}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Windows")!=-1&&navigator.userAgent.indexOf("Windows 3")==-1&&document.all)
{document.write('<scr'+'ipt language=VBScript>\n Ads_vbCV=10\nAds_vbMV=1\nDo\nOn Error Resume Next\n');document.write('Ads_vbBF=(IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash."&Ads_vbCV)))\n');document.write('If Ads_vbBF=true Then Exit Do\nAds_vbCV=Ads_vbCV-1\nLoop While Ads_vbCV>=Ads_vbMV\n </scr'+'ipt>');QQRc=Ads_vbCV;}QQaB=QQRc;return QQRc;}function QQsD(QQSc)
{if(QQrB)
return '<div id='+QQSc+' style="position:absolute;left:-1000;top:-1000;">';else
return '';}function QQtD()
{if(QQrB)
return '</div>';else
return '';}function QQuD(QQTc)
{var QQUc,QQVc;if(window.innerHeight)
{QQUc=QQTc.x;QQVc=QQTc.y;}else
{if(QQTc.offsetLeft)
{QQTc=QQTc;QQUc=QQTc.offsetLeft;QQNj=QQTc.offsetParent;while(QQNj!=null)
{QQUc+=QQNj.offsetLeft;QQNj=QQNj.offsetParent;}QQVc=QQTc.offsetTop;QQNj=QQTc.offsetParent;while(QQNj!=null)
{QQVc+=QQNj.offsetTop;QQNj=QQNj.offsetParent;}}else
return [-1000,-1000];}return [QQUc,QQVc];}function QQvD(QQWc,QQA,QQf,QQg)
{var QQXc;var QQTc=document.images[QQA];var QQYc=QQuD(QQTc);QQTc.width=QQf;QQTc.height=QQg;if(QQrB)
QQXc=document.getElementById(QQWc).style;else if(document.layers)
QQXc=document.layers[QQWc];else
QQXc=document.all[QQWc].style;QQXc.left=QQYc[0];QQXc.top=QQYc[1];if (QQrB) QQXc.display='block';else if(document.layers) QQXc.visibility='show';else QQXc.visibility='visible';}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000050-2)
if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=QQvC;gbolSUXX25067=false;var Ads_ModulMain=true;if(typeof(Ads_ModulEffects)=='undefined')
Ads_ModulEffects=false;var QQqA,QQrA,QQsA,QQtA,QQuA,QQvA,QQwA,QQxA;var QQyA,QQzA,QQaB,QQbB,QQcB,QQdB;var QQeB=false;var QQfB=[];var QQgB=[];var QQhB=[];var QQiB=[];var QQjB=[];var QQkB=[];var QQlB=[];var QQmB=navigator.userAgent.toLowerCase();var QQnB=(QQmB.indexOf("msie")!=-1);var QQoB=((QQmB.indexOf("win")!=-1)||(QQmB.indexOf("16bit")!=-1));var QQpB=(QQmB.indexOf("mac")!=-1);var QQqB=(navigator.appName.indexOf('icrosoft')!=-1);var QQrB=(typeof(document.getElementsByTagName)!='undefined'&&typeof(document.createElement)!='undefined')?1:0;var QQsB=true;var QQtB='';var QQuB=0;var QQvB=[];var QQwB=0;var QQxB=0;var QQyB=[];var QQzB;var QQaC=[];var QQbC=[];var QQcC=[];var QQdC=[];var QQeC=[];var QQfC=[];var QQgC=[];var QQhC=[];var Ads_LinkUrl,Ads_CountUrl,Ads_CountUrl_ne,Ads_ClickUrl,Ads_T,Ads_T_OW,iid,bid,rdm;var Ads_Data=[];if(typeof(Ads_FXPL)=='undefined'){var Ads_FXPL=false;}Ads_T_OW=[];var QQiC,QQjC,Ads_gintCurVersion;var QQkC='toolbar=yes,directories=yes,status=yes,scrollbars=yes,resizable=yes,menubar=yes,location=yes';function gotoSite(){window.open(QQiC,'flashwin',QQkC);}function emosite(){window.open(QQiC,'flashwin',QQkC);}function FlashClick(){window.open(QQiC,'flashwin',QQkC);}function link1(){window.open(QQiC,'flashwin',QQkC);}function gotoURL(QQa){window.open(QQjC+escape(QQa),'flashwin',QQkC);}function QQlC()
{Ads_kid=0;Ads_bid=0;Ads_cmd='';}function QQmC(QQa)
{QQa=QQnD(QQa,'[par]',escape(Ads_par));QQa=QQnD(QQa,'[keyword]',escape(Ads_wrd));QQa=QQnD(QQa,'[timestamp]',Ads_Timestamp);if (typeof(Ads_CountUrl)!='undefined')
{QQa=QQnD(QQa,'[clickurl]',escape(Ads_CountUrl));QQa=QQnD(QQa,'[clickurl_plain]',Ads_CountUrl);QQa=QQnD(QQa,'[clickurl_double]',escape(escape(Ads_CountUrl)));QQa=QQnD(QQa,'[clickurl_ne]',escape(Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne='));QQa=QQnD(QQa,'[clickurl_plain_ne]',Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=');QQa=QQnD(QQa,'[clickurl_double_ne]',escape(escape(Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=')));}QQa=QQnD(QQa,'[web_id]',Ads_wid);QQa=QQnD(QQa,'[web_external_id]',escape(Ads_xwid));QQa=QQnD(QQa,'[con_id]',Ads_iid);QQa=QQnD(QQa,'[con_external_id]',escape(Ads_xiid));QQa=QQnD(QQa,'[ban_id]',Ads_sbid);QQa=QQnD(QQa,'[cam_id]',QQtA);return QQa;}function QQnC(QQa,QQb)
{QQoD(1,'QQnC QQb',QQb);return QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQwC()+'&'+QQb+'&dat='+escape(QQa);}function QQoC(QQc,QQd,QQe,QQf,QQg)
{var QQh;if(QQuB<2)
{QQuB++;QQh=QQuB+1;QQtB+='&kid'+QQh+'='+QQc;QQtB+='&bid'+QQh+'='+QQd;QQtB+='&iid'+QQh+'='+Ads_iid;QQtB+='&dlv'+QQh+'='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd;if(QQuA!=0)
QQtB+='&sid'+QQh+'='+QQuA;arrIntern=QQzC(QQe);QQwB=arrIntern[1];QQxB=arrIntern[2];Ads_iid=arrIntern[1];Ads_kid=arrIntern[2];Ads_bid=(arrIntern.length<4)?0:arrIntern[3];Ads_par=(arrIntern.length<5)?Ads_par:unescape(arrIntern[4]);Ads_xp=(arrIntern.length<6||Ads_xp!='')?Ads_xp:arrIntern[5];Ads_yp=(arrIntern.length<7||Ads_yp!='')?Ads_yp:arrIntern[6];Ads_xp1=(arrIntern.length<8||Ads_xp1!='')?Ads_xp1:arrIntern[7];Ads_yp1=(arrIntern.length<9||Ads_yp1!='')?Ads_yp1:arrIntern[8];Ads_xl=0;Ads_yl=0;QQaD(QQfB[Ads_sec]+'/dat/cjf/'+QQpD(Ads_iid)+'.js');}else
{QQtB='';QQuB=0;QQlC();}}function QQpC(QQi)
{var QQj=[];var QQk=QQi.length;var QQl;var QQm='';var QQn='';for(QQl=0;QQl<QQk;QQl+=2)
{QQm=QQi[QQl+1];if(Ads_cnturl!='')
{QQn=QQnD(Ads_cnturl,'[url]',escape(QQm));QQm=QQnD(QQn,'[url_plain]',QQm);}QQj[QQl/2+1]=Ads_CountUrl+escape(QQm)+'&bidx='+QQi[QQl];}return QQj;}function SAS()
{var QQo=false;QQtC();QQo=QQuC();if (QQo==true)
{if((document.cookie.toLowerCase().indexOf('bndlvl')==-1)&&((IAS[13]&4)>0))
QQuE();else
QQqC();}else
{QQsB=false;QQoD(1,'Waiting for asldata.','');}}function QQqC()
{var QQp;if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=QQvC;if(((Ads_nid==631)||(Ads_nid==668))&&(NUM_FARM==1))
{ QQfB[0]=['http://e.as-eu.falkag.net'];QQiB[0]=QQfB[0];}if((Ads_nid==80)&&(NUM_FARM==3))
{ QQfB[0]=['http://e.as-us.falkag.net'];QQiB[0]=QQfB[0];}var QQq='undefined';for (intI=0;intI<Ads_T.length;intI++)
{if (typeof(Ads_T_OW)!=QQq)
{if (typeof(Ads_T_OW[intI])!=QQq)
{QQoD(1,'Overwriting Targeting AdsT['+intI+'] ('+Ads_T[intI]+') with',Ads_T_OW[intI]);Ads_T[intI]=Ads_T_OW[intI];}}}if(typeof(Ads_cmd)==QQq) Ads_cmd='';if(typeof(Ads_kid)==QQq) Ads_kid=0;if(typeof(Ads_bid)==QQq) Ads_bid=0;if(typeof(Ads_xl)==QQq) Ads_xl=0;if(typeof(Ads_yl)==QQq) Ads_yl=0;if(typeof(Ads_xp)==QQq) Ads_xp='';if(typeof(Ads_yp)==QQq) Ads_yp='';if(typeof(Ads_xp1)==QQq) Ads_xp1='';if(typeof(Ads_yp1)==QQq) Ads_yp1='';if(typeof(Ads_opt)==QQq) Ads_opt=0;if(typeof(Ads_wrd)==QQq) Ads_wrd='';if(typeof(Ads_prf)==QQq) Ads_prf='';if(typeof(Ads_par)==QQq) Ads_par='';if(typeof(Ads_cnturl)==QQq) Ads_cnturl='';if(typeof(Ads_ref)==QQq) Ads_ref=0;if(typeof(Ads_anc)==QQq) Ads_anc='';if(typeof(Ads_cmb)==QQq) Ads_cmb=[];if(typeof(Ads_uid)==QQq) Ads_uid='';if(typeof(Ads_bgc)==QQq) Ads_bgc='';Ads_cmd=Ads_cmd.toLowerCase();if(Ads_ref==0)
Ads_ref=IAS[12];if(Ads_bgc=='')
{if(typeof(IAS[16])!=QQq)
Ads_bgc=IAS[16];}QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+Ads_kid+'&wrd='+escape(Ads_wrd) +'&bid='+Ads_bid+'&prf='+escape(Ads_prf) +'&xl='+Ads_xl+'&par='+escape(Ads_par) +'&yl='+Ads_yl+'&cnturl='+Ads_cnturl+'&debug='+Ads_debug +'&xp='+Ads_xp+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+Ads_yp+'&ref='+Ads_ref +'&xp1='+Ads_xp1+'&yp1='+Ads_yp1+'&opt=';var QQr='" width="'+Ads_xl+'" height="'+Ads_yl+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>';if(Ads_ref>0)
{document.write('<iframe src="'+QQp+Ads_opt+QQr);Ads_ref=0;return;}QQeF();if((Ads_bgc!='')&&(Ads_bgc!='-1'))
document.body.style['backgroundColor']='#'+Ads_bgc;if(((IAS[13]&8)>0)&&(QQvE[10]==0))
QQrE();QQqA='';QQrA='';QQtA=0;QQuA=0;QQvA='';QQsA=-1;if(NUM_FARM==3)
KAS[KAS.length]=[-1,100,-1,100,[],0,0,0,0,100];if((Ads_kid==0)||(Ads_kid==''))
QQsA=QQzD();else
{QQk=KAS.length;QQsA=0;while((QQsA<QQk)&&(KAS[QQsA][0]!=Ads_kid))
QQsA++;if(QQsA==QQk)
QQsA=-1;}if((Ads_opt&256)!=0)
{if(QQsA!=-1)
Ads_skid=KAS[QQsA][0];else
Ads_skid=0;}else
{if(QQsA!=-1)
{QQtA=KAS[QQsA][0];QQuA=KAS[QQsA][6];if(QQuA!=0)
QQvA='&sid='+QQuA;if(QQtA>0)
{QQaD(QQfB[Ads_sec]+'/dat/bjf/'+QQpD(QQtA)+'.js');}else
DAS();}else
{DAS();}}}function DAS()
{var QQs,QQk,QQt,QQu,QQv,QQw,QQx,QQy,QQz;QQy=['',''];QQz=[];var QQA='';var QQB=['_blank','_self','_parent','_top'];Ads_Timestamp=QQlD();var QQd=0;var QQC,QQf,QQg;if(IAS[9]==1)
{QQC='adsolut.gif';QQf=234;QQg=60;}else
{QQC='trpix.gif';QQf=1;QQg=1;}QQbB=QQmA[NUM_FARM];if(IAS[9]==4)
QQbB='Werbung';if (NUM_FARM==2){QQbB='onmouseover="self.status=\'\';return true;" ';}else{QQbB='onmouseover="self.status=\''+QQbB+'\';return true;" ';}if(IAS[9]==5)
QQbB='';var QQD=1;var QQa='http://www.falkag.de';// Ziel-Url
var QQE=(NUM_FARM==2)?'':'Falk AdSolution';var QQF=0;var QQG='';var QQH='';var QQI='';var QQJ='';var QQK='';var QQL=0;var QQM=0;var QQN=0;var QQO=0;var QQP=1;var QQQ=2;var QQe='';var QQR='';var QQi=[];var QQS=0;var QQT='';var QQU='';var QQV=false;var QQW=0;var QQX=false;var QQY,QQZ,QQAa,QQBa,QQCa,QQDa,QQEa,QQFa,QQGa,QQHa;if(QQtA!=0)
{if((Ads_bid==0)||(Ads_bid==''))
QQs=QQaE(QQsA,QQtA);else
{QQk=BAS.length;QQs=0;while((BAS[QQs][0]!=Ads_bid)&&(QQs<QQk))
QQs++;if(QQs==QQk)
QQs=-1;}if(QQs!=-1)
QQd=BAS[QQs][0];}if(QQd>0)
{QQD=BAS[QQs][3];QQC=BAS[QQs][4];QQa=BAS[QQs][5];QQE=BAS[QQs][6];QQF=BAS[QQs][12];QQG=BAS[QQs][7];QQH=BAS[QQs][8];QQI=BAS[QQs][9];QQJ=BAS[QQs][10];QQK=BAS[QQs][11];QQf=BAS[QQs][13];QQg=BAS[QQs][14];QQL=BAS[QQs][15];QQM=BAS[QQs][16];QQP=BAS[QQs][17];QQQ=BAS[QQs][18];QQe=BAS[QQs][19];QQR=BAS[QQs][20];QQi=BAS[QQs][22];QQS=BAS[QQs][23];QQT=BAS[QQs][24];QQU=BAS[QQs][25];QQW=BAS[QQs][27];if (!QQeB)
QQeB=(BAS[QQs][26]==1);Ads_klist+=QQtA+'#';QQv=KAS[QQsA][4][25];if(QQv>0)
{if(typeof(Ads_fcount[QQv])=='undefined')
Ads_fcount[QQv]=1;else
Ads_fcount[QQv] ++;}}if(QQtA>0)
QQy=QQhF(QQtA,QQsA,QQd,QQs,((QQF&4096)>0));if(QQtA==-1)
{QQtA=99999999;QQd=99999999;}QQz=QQgD(QQtA,QQd,QQy);QQoD(1,'Count-String [Click/Impression]',QQz[0]+'/'+QQz[1]);Ads_skid=QQtA;Ads_sbid=QQd;QQH=(QQH=='')?QQa:QQH;QQY=(QQF&24);QQZ=QQB[QQF&3];QQCa=((QQF&64)>0)&&((Ads_opt&64)==0);QQAa=(QQF&128)>0;QQBa=(QQF&512)>0;QQV=(QQT=='_search')||(QQT=='_media');QQDa=((QQF&1024)>0)&&Ads_ModulEffects;QQEa=((QQF&8192)>0);QQUj=((Ads_opt&2)>0);QQFa=(QQF&2048)>0;QQGa=(QQR.length>0);QQX=(QQW==0)?false:true;QQf=(Ads_xl>0)?Ads_xl:QQf;QQg=(Ads_yl>0)?Ads_yl:QQg;QQL=(Ads_xp!='')?Ads_xp:QQL;QQM=(Ads_yp!='')?Ads_yp:QQM;QQN=(Ads_xp1!='')?Ads_xp1:QQN;QQO=(Ads_yp1!='')?Ads_yp1:QQO;QQyA=(QQF&4096)>0;Ads_opt|=(QQF&16384)>0?64:0;Ads_opt|=IAS[3]*32;if (QQX&&Ads_cmd!='win')
{var QQIa='nid='+Ads_nid+'&iid='+Ads_iid+'&bid='+QQd+'&rdm='+QQlD();document.write(QQjD(1,QQIa));}if(Ads_anc!='')
{QQw=true;QQA=Ads_anc;Ads_anc='';}QQa=QQmC(QQa);QQH=QQmC(QQH);if(Ads_cnturl!='')
{QQHa=QQnD(Ads_cnturl,'[url]',escape(QQa));QQa=QQnD(QQHa,'[url_plain]',QQa);QQHa=QQnD(Ads_cnturl,'[url]',escape(QQH));QQH=QQnD(QQHa,'[url_plain]',QQH);}if(QQvB.length!=0)
{QQqA+=QQvB[13];QQrA+=QQvB[14];}if((QQD==3)||(QQD==4)||(QQD==8))
{Ads_LinkUrl=QQa;Ads_CountUrl=QQnC('',QQz[0]);Ads_CountUrl_ne=Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=';Ads_ClickUrl=Ads_CountUrl+escape(QQa);Ads_MultiUrl=QQpC(QQi);Ads_ViewCode=QQjD(0,QQz[1]);Ads_ViewUrl=QQhD()+QQz[1];}if(QQD==1)
QQI=QQiB[Ads_sec]+'/dat/bgf/'+QQC;if(QQvB.length!=0)
{if(!QQAa)
{QQAa=QQvB[0];QQCa=QQvB[1];QQBa=QQvB[2];QQQ=QQvB[3];QQDa=QQvB[4];QQEa=QQvB[5];}if(!QQGa)
{QQGa=QQvB[6];QQR=QQvB[7];}QQL=QQvB[8];QQM=QQvB[9];QQN=QQvB[16];QQO=QQvB[17];QQY=QQvB[10];IAS[2]=QQvB[11];IAS[11]=QQvB[12];QQA=QQvB[15];QQw=(QQA!='');QQvB=[];}if(QQD==5)
{QQvB=[QQAa,QQCa,QQBa,QQQ,QQDa,QQEa,QQGa,QQR,QQL,QQM,QQY,IAS[2],IAS[11],QQqA,QQrA,QQA,QQN,QQO];QQAa=false;QQGa=false;QQw=false;IAS[2]=0;}if((Ads_cmd=='lnk')&&(QQD!=5))
{self.location.href=QQnC(QQa,QQz[0]);QQAa=false;QQGa=false;QQw=false;QQD=6;return;}if(QQAa&&!QQV)
{if (!QQUj)
QQt=QQlI(QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,'');else
QQt=window;if(QQCa)
{if(window.innerHeight)
{QQf=QQt.innerWidth;QQg=QQt.innerHeight;}else
{QQf=QQt.document.body.clientWidth;QQg=QQt.document.body.clientHeight;}}if (!QQUj||(QQUj&&Ads_cmd=='win'))
if(QQBa&&(QQQ==0))
QQt.blur();else if(QQBa)
QQt.setTimeout('window.blur();',QQQ*1000);}else
QQt=window;if(QQw)
document.write(QQsD('Ads_place'+Ads_iid));else if(Ads_ModulEffects&&QQGa)
{if(QQY==16)
QQY=1;else if(QQY==24)
QQY=2;else
QQY=0;QQsH(Ads_iid,QQf,QQg,QQL,QQM,QQY,QQR,QQAa,QQt);QQtH(Ads_iid,Ads_sec);}QQoD(1,'Banner-Typ/PopUp',QQD+'/'+QQAa);QQnI(QQtA,QQd,QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,'',QQUj);if (!QQUj||(QQUj&&(Ads_cmd =='win')))
{if(QQD<2)
QQfI(QQt,QQAa,QQz,QQI,QQa,QQZ,QQf,QQg,QQE,QQV,QQT,QQd,QQL,QQM);else if(QQD==2)
QQgI(QQt,QQAa,QQz,QQC,QQa,QQZ,QQf,QQg,QQE,QQG,QQH,QQFa,QQP,QQU);else if(QQD==3)
QQhI(QQt,QQAa,QQz,QQtA,QQd,QQy,QQGa,QQf,QQg,QQS,QQT,QQw,'/dat/brf/',0,QQV,QQUj);else if(QQD==4)
QQiI(QQt,QQAa,QQz,QQJ,QQK,QQGa,QQf,QQg,QQw);else if(QQD==5)
QQoC(QQtA,QQd,QQe,QQf,QQg);else if(QQD==8)
QQhI(QQt,QQAa,QQz,QQtA,QQd,QQy,QQGa,QQf,QQg,QQS,QQT,QQw,'/dat/bfx/',parseInt(QQe,10),QQV,QQUj);}QQoD(3,'Banner-display finished');QQsE();if(QQw)
{document.write(QQtD());setInterval('QQvD("Ads_place'+Ads_iid+'","'+QQA+'",'+QQf+','+QQg+');',20);}if(Ads_ModulEffects&&QQGa)
QQuH(Ads_iid);if(QQD!=5)
QQlC();Ads_idl+='#'+Ads_iid+'#';if((IAS[2]>0)&&(Ads_idl.indexOf('#'+IAS[2]+'#')==-1)&&(IAS[11]>(Math.random()*100)))
{Ads_kid=0;Ads_bid=0;Ads_xl=0;Ads_yl=0;QQaD(QQfB[Ads_sec]+'/dat/cjf/'+QQpD(IAS[2])+'.js');}QQk=Ads_cmb.length;for(QQl=0;QQl<QQk;QQl++)
{if(Ads_cmb[QQl]!='')
{QQx=Ads_cmb[QQl];Ads_cmb[QQl]='';QQl=QQk;Ads_pth='';Ads_iid='';eval(QQx);if(Ads_pth!='')
QQaD(QQfB[Ads_sec]+'/dat/njf/'+Ads_pth+'.js');else
QQaD(QQfB[Ads_sec]+'/dat/cjf/'+QQpD(Ads_iid)+'.js');}}}function CAS()
{QQrC(0);}function CASF()
{var QQJa=new Date();Ads_T=[0,0,'',0,0,'','','','',QQJa,0,0,0,0];QQrC(1);}function QQrC(QQKa)
{if(typeof(Ads_debug)=='undefined') Ads_debug=0;var QQLa=new Date(Ads_T[9]);var QQMa=new Date();Ads_T[9]=QQLa-QQMa;var QQNa=Ads_T[0]+'#'+Ads_T[1]+'#'+Ads_T[2]+'#'+Ads_T[3]+'#'+Ads_T[4]+'#'+Ads_T[5]+'#'+Ads_T[6]+'#'+escape(Ads_T[7])+'#'+escape(Ads_T[8])+'#'+Ads_T[9]+'#'+Ads_T[10]+'#'+Ads_T[11]+'#'+Ads_T[12]+'#'+Ads_T[13];document.cookie='ASLTRG'+NUM_FARM+'='+QQNa+QQeD(60*((QQKa==0)? 24:1));Ads_Data[NUM_FARM]=Ads_T;QQoD(1,'Load targeting-infos from server ('+((QQKa==0)? 'Origin':'Failover')+')',QQNa);if (QQsB==false)
{QQsB=true;SAS();}}function LAS(QQOa)
{Ads_iid=0;var QQb='pth='+QQOa+'&xl='+Ads_xl+'&yl='+Ads_yl;if(typeof(Ads_channels)!='undefined')
QQb+='&chn='+escape(Ads_channels);QQyA=false;document.write(QQjD(0,QQb));}function QQsC()
{QQwA=new Date();QQaB=-1;QQdB=0;document.cookie='BSUID=1'+QQeD(60*24*30);QQzA=false;if(typeof(Ads_debug)=='undefined') Ads_debug=0;if(typeof(Ads_sec)=='undefined') Ads_sec=0;if(typeof(Ads_klist)!='string') Ads_klist='';if(typeof(Ads_fcount)!='object') Ads_fcount=[];if(typeof(Ads_idl)!='string') Ads_idl='';if(typeof(garrIFrames)=='undefined') garrIFrames=[];QQoD(3,'Global Init');QQoD(1,'VAS Build Version:',Ads_Build);}function QQtC()
{if(typeof(NUM_FARM)=='undefined')
NUM_FARM=1;if(typeof(Ads_farmid)!='undefined')
NUM_FARM=Ads_farmid;QQoD(1,'Setting configuration for farm',NUM_FARM);QQfB=[QQbA[NUM_FARM],QQcA[NUM_FARM]];QQgB=[QQhA[NUM_FARM],QQiA[NUM_FARM]];QQhB=[QQjA[NUM_FARM],QQkA[NUM_FARM]];QQiB=[QQdA[NUM_FARM],QQeA[NUM_FARM]];QQjB=[QQfA[NUM_FARM],QQgA[NUM_FARM]];}function QQuC()
{var QQNa=document.cookie+';';var QQPa=(QQNa.indexOf('BSUID=')!=-1);var QQQa=QQNa.indexOf('ASLTRG'+NUM_FARM+'=');var QQRa,QQZ;if (typeof(Ads_Data[NUM_FARM])!='undefined')
{QQoD(1,'Load targeting-infos targeting array ['+NUM_FARM+']',Ads_Data[NUM_FARM]);Ads_T=Ads_Data[NUM_FARM];return true;}if(QQQa!=-1)
{QQRa=QQNa.indexOf(';',QQQa);QQZ=QQNa.substring(QQQa+8,QQRa);Ads_T=QQZ.split('#');Ads_T[7]=unescape(Ads_T[7]);Ads_T[8]=unescape(Ads_T[8]);Ads_Data[NUM_FARM]=Ads_T;QQoD(1,'Load targeting-infos from cookie',QQZ);return true;}else
{QQoD(1,'#-#ASLDATA-load start','');QQaD(QQhB[Ads_sec]+ (QQPa?('?rdm='+QQlD()):''));QQoD(1,'#-#ASLDATA-load ende','');return false;}}function QQvC(QQSa,QQTa,QQUa)
{return true;}function QQwC()
{var QQVa=(QQyA?1:0);QQVa+=((QQeB)?2:0);QQoD(1,'FLG',QQVa);return QQVa;}function QQxC(QQWa,QQXa)
{if ((QQWa==QQwB)&&(QQXa==QQxB))
return true;else
return false;}function QQyC(QQYa,QQZa)
{var QQAb;var QQBb;QQBb=false;if(!isNaN(QQYa))
{QQAb=parseInt(QQYa);QQBb=QQAb>=0&&(QQZa||QQAb>0);}return QQBb;}function QQzC(QQCb)
{var QQDb,QQEb;var QQFb,QQGb,QQHb,QQIb,QQJb,QQKb;var QQY,QQLb,QQMb,QQNb,QQOb;var QQPb;var QQQb;QQDb=QQCb.split('-');QQQb=false;QQEb=[];QQPb=true;if(QQDb[0]!=null&&QQDb[1]!=null)
{QQFb=QQDb[0];QQGb=QQDb[1];QQPb=QQPb&&QQyC(QQGb,false);if(QQPb&&QQDb[2]!=null)
{QQHb=QQDb[2];QQPb=QQyC(QQHb,false);if(QQPb&&QQDb[3]!=null)
{QQIb=QQDb[3];QQPb=QQyC(QQIb,true);if(QQPb&&QQDb[4]!=null)
{QQJb=QQDb[4];if(QQPb&&QQDb.length>5)
{QQY=5;while(QQPb&&QQY<QQDb.length)
{if(QQDb[QQY]==''&&QQDb[QQY+1]!=null)
{QQKb=QQDb[QQY+1];QQPb=QQyC(QQKb,true);QQEb[QQEb.length]='-'+QQKb;QQY=QQY+2;}else
{QQKb=QQDb[QQY];QQPb=QQyC(QQKb,true);QQEb[QQEb.length]=QQKb;QQY=QQY+1;}}QQPb=QQPb&&(QQEb.length==0||QQEb.length==2||QQEb.length==4);}}}}if(QQPb)
{QQQb=[QQFb,QQGb,QQHb,QQIb,QQJb];for (var intI=0;intI<QQEb.length;intI++)
{QQQb[QQQb.length]=QQEb[intI];}}}return QQQb;}QQsC();// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000050-2)
function QQeI(QQDh,QQOj)
{return (QQDh==0)?'':' '+QQOj+'="'+QQDh+'"';}function QQfI(QQt,QQAa,QQz,QQI,QQa,QQZ,QQf,QQg,QQE,QQV,QQT,QQd,QQL,QQM)
{QQI=QQmC(QQI);if(QQAa&&QQV&&!QQUj)
{QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+QQtA+'&wrd='+escape(Ads_wrd) +'&bid='+QQd+'&prf='+escape(Ads_prf) +'&xl='+QQf+'&par='+escape(Ads_par) +'&yl='+QQg+'&cnturl='+Ads_cnturl+'&debug=0' +'&xp='+QQL+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+QQM+'&ref='+Ads_ref+'&opt=' +2 +'&cmd=win';QQoD(1,'Sidebar',QQp);QQtSide=window.open(QQp,QQT);}else
{if(QQAa)
QQjI(QQt,QQE);QQt.document.write('<a href="'+QQnC(QQa,QQz[0]) +'" target="'+QQZ+'" '+QQbB+'onmouseout="self.status=\'\';return true;">');QQt.document.write('<img src="'+QQI+'"'+QQeI(QQf,'width')+QQeI(QQg,'height')+' border="0" id="Ads_img'+Ads_iid+'" name="Ads_img'+Ads_iid+'" alt="'+QQE+'"></a>');QQkD(QQt,QQz[1]);if(QQAa)
QQkI(QQt);}if (QQxC(Ads_iid,QQtA))
{QQtB='';QQuB=0;}}function QQgI(QQt,QQAa,QQz,QQC,QQa,QQZ,QQf,QQg,QQE,QQG,QQH,QQFa,QQP,QQU)
{var QQRj=QQnD(QQz[0],'&rdm='+Ads_Timestamp,'');if(QQAa)
QQjI(QQt,QQE);QQa=QQnC(QQa,QQRj);QQH=QQnC(QQH,QQRj);QQC=QQiB[Ads_sec]+'/dat/bgf/'+QQC;QQG=QQiB[Ads_sec]+'/dat/bgf/'+QQG;QQiC=QQa;QQjC=QQnC('',QQRj);var QQSj=QQC;if(typeof(QQU)=='undefined') QQU='';if(QQU=='')
QQSj+='?clickTag='+escape(QQa)+'&url='+escape(QQa);else if(QQU!='0')
QQSj+='?'+QQU+'='+escape(QQa);var QQQc;if(QQP<=QQrD(1))
{QQt.document.write('<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http'+((Ads_sec==1)?'s':'')+'://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0" id=banner'+QQeI(QQf,'width')+QQeI(QQg,'height')+'">');QQt.document.write('<PARAM NAME=movie VALUE="'+QQSj+'"><PARAM NAME=play VALUE=true><PARAM NAME=autoplay VALUE=true><PARAM NAME=wmode VALUE=opaque><PARAM NAME=quality VALUE=autohigh><PARAM name=scale value=exactfit>');QQt.document.write('<EMBED src="'+QQSj+'" quality=autohigh autoplay=true play=true wmode=opaque scale=exactfit swLiveConnect=TRUE'+QQeI(QQf,'width')+QQeI(QQg,'height')+' TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"></EMBED></OBJECT>');}else
{QQt.document.write('<a href="'+QQH+'" target="'+QQZ+'" '+QQbB+' onmouseout="self.status=\'\';return true;"><img src="'+QQG+'"'+QQeI(QQf,'width')+QQeI(QQg,'height')+' border="0" alt="'+QQE+'"></a>');}QQkD(QQt,QQz[1]);if(QQAa)
QQkI(QQt);if (QQxC(Ads_iid,QQtA))
{QQtB='';QQuB=0;}}function QQhI(QQt,QQAa,QQz,QQc,QQd,QQy,QQGa,QQf,QQg,QQS,QQT,QQw,QQOa,QQTj,QQV,QQUj)
{var QQC=QQfB[Ads_sec]+QQOa+QQpD((QQTj>0)?QQTj:((QQS==0)?QQd:QQS));var QQVj,QQAg;var QQWj=[];QQWj=QQfD(QQc,QQd,QQy);iid=Ads_iid;bid=QQd;rdm=QQWj[2];if(QQAa||((QQGa||QQw)&&(QQqB||QQrB)))
{var QQXj='*';for(QQAg=1;QQAg<Ads_MultiUrl.length;QQAg++)
{QQa=Ads_MultiUrl[QQAg];QQXj+=QQa.substring(Ads_CountUrl.length,QQa.length)+'*';}QQVj=Ads_wid+'#'+Ads_iid+'#'+QQc+'#'+QQd+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+(QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQwC()+'&')+'#'+Ads_LinkUrl+'#'+QQXj+'#'+QQhD();}if(QQAa&&QQV&&!QQUj)
{window.open(QQC+'.html?'+escape(QQVj),QQT);}else if(QQAa)
{QQt.location.href=QQC+'.html?'+escape(QQVj);}else if((QQGa||QQw)&&(QQqB||QQrB))
{document.write('<iframe src="'+QQC+'.html?'+escape(QQVj)+'" width="'+QQf+'" height="'+QQg+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{rdm=QQWj[0];if(QQTj>0)
{Ads_xl=QQf;Ads_yl=QQg;QQkD(QQt,QQz[1]);if ((Ads_opt&4096)>0)
{QQoD(1,'Serve AFX Out Of Frame','');var QQXj='*';for(QQAg=1;QQAg<Ads_MultiUrl.length;QQAg++)
{QQa=Ads_MultiUrl[QQAg];QQoD(1,'Ads_MultiUrl['+QQAg+']',QQa.substring(Ads_CountUrl.length,QQa.length));QQaShort=QQa.substring(Ads_CountUrl.length,QQa.length);QQoD(1,'Index of',QQaShort.indexOf(".falkag.net/dat/bgf/trpix.gif&bidx="));if (QQaShort.indexOf(".falkag.net/dat/bgf/trpix.gif&bidx=")>=0)
{QQXj+='PX'+QQaShort.substring(QQaShort.indexOf('&')+5,QQaShort.length)+'*';}else
{QQXj+=QQaShort+'*';}}QQoD(1,'QQXj',QQXj);QQVj=Ads_wid+'#'+Ads_iid+'#'+QQc+'#'+QQd+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+(QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQwC()+'&')+'#'+Ads_LinkUrl+'#'+QQXj+'#'+QQhD()+'#'+NUM_FARM+'#'+QQfB[Ads_sec]+'#'+QQTj;var QQYj=document.referrer;var QQZj='';var QQAk='';var QQBk=QQYj.indexOf('://');if (QQBk>-1)
{QQZj=QQYj.substring(0,(QQBk+3));QQAk=QQYj.substring((QQBk+3),QQYj.length);var QQBk=QQAk.indexOf('/');if (QQBk>-1)
QQAk=QQAk.substring(0,QQBk);}QQoD(1,'Loading ',QQZj+QQAk+'/afx_frame.html?'+ escape(QQVj));document.write('<iframe src="'+QQZj+QQAk+'/afx_frame.html?'+escape(QQVj)+'" width="1" height="1" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{if ((typeof(Ads_FXPL)=='undefined')||(Ads_FXPL==false))
{QQaD(QQfB[Ads_sec]+'/dat/dlv/afxplay.js');Ads_FXPL=true;}QQaD(QQC+'.js');}}else
QQaD(QQC+'.js');}if (QQxC(Ads_iid,QQtA))
{QQtB='';QQuB=0;}}function QQiI(QQt,QQAa,QQz,QQJ,QQK,QQGa,QQf,QQg,QQw)
{QQK=QQmC(unescape(QQK));QQJ=QQmC(unescape(QQJ));if(QQAa)
QQt.location.href=QQJ;else
{if(((QQGa||QQw)&&QQqB)||(QQK==''))
document.write('<iframe src="'+QQJ+'" width="'+QQf+'" height="'+QQg+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');else
QQaD(QQK);}QQkD(window,QQz[1]);if (QQxC(Ads_iid,QQtA))
{QQtB='';QQuB=0;}}function QQjI(QQt,QQE)
{QQt.document.open();QQt.document.write('<html><head><title>'+QQE+'</title></head><body topmargin="0" leftmargin="0" rightmargin="0" marginwidth="0" marginheight="0"><table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" align="center"><tr><td valign="middle"><center>');}function QQkI(QQt)
{QQt.document.write('</center></td></tr></table></body></html>');QQt.document.close();}function QQlI(QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,QQT)
{var QQu='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var QQCk='Ads_Popup'+Ads_iid;var QQDk,QQEk;var QQFk=0;var QQGk=0;if (!QQV&&QQT!='')
QQCk=QQT;QQu=QQmI(QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,QQT,QQUj);if((Ads_opt&32)>0)
QQCk+=''+Math.round(Math.random()*100000);QQt=open('',QQCk,QQu);if(QQCa&&(!QQnB))
QQt.moveTo(0,0);if(QQDa)
QQbI(QQt,QQf,QQg);return QQt;}function QQmI(QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,QQT,QQUj)
{var QQu='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var QQCk='Ads_Popup'+Ads_iid;var QQDk,QQEk;var QQFk=0;var QQGk=0;if (!QQV&&QQT!='')
QQCk=QQT;if(QQCa)
{if (QQoB)
{QQFk=10;QQGk=30;}else if (QQpB)
{QQFk=20;QQGk=35;}QQu+=',scrollbars=no,resizable=no,width='+(screen.availWidth-QQFk)+',height='+(screen.availHeight-QQGk)+',screenX=0,screenY=0';if(QQnB)
QQu='fullscreen=yes';}else
{if(QQDa)
QQu+=',resizable=yes,width=90,height=70,innerWidth=90,innerHeight=70';else
QQu+=',resizable=no,width='+QQf+',height='+QQg;if(QQEa)
QQu+=',scrollbars=yes';else
QQu+=',scrollbars=no';if((Ads_opt&64)>0)
QQu='locationbar=yes,scrollbars=yes,directories=yes,statusbar=yes,toolbar=yes,location=yes,menubar=yes,personalbar=yes,resizable=yes,width='+QQf+',height='+QQg;if(QQY==16)
{QQL=(screen.width-QQf-25)*QQL/100;QQM=(screen.height-QQg-50)*QQM/100;}else if(QQY==24)
{QQL=(screen.width-QQf-25)*Math.random();QQM=(screen.height-QQg-50)*Math.random();}if (!QQqB)
QQu+=",screenX="+QQL+",screenY="+QQM;else
QQu+=",left="+QQL+",top="+QQM;}return QQu;}function QQnI(QQtA,QQd,QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,QQT,QQUj)
{var QQHk='';QQHk='<scr'+'ipt language="JavaScript">'+'function Ads_PopUp() {';if (Ads_cmd!='win'&&QQUj&&(QQd>0))
{QQoD(1,'POP ON EXIT','');var QQCk='Ads_Popup'+Ads_iid;if (!QQV&&QQT!='')
QQCk=QQT;if((Ads_opt&32)>0)
QQCk+=''+Math.round(Math.random()*100000);QQu=QQmI(QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,'',true);QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+QQtA+'&wrd='+escape(Ads_wrd) +'&bid='+QQd+'&prf='+escape(Ads_prf) +'&xl='+QQf+'&par='+escape(Ads_par) +'&yl='+QQg+'&cnturl='+Ads_cnturl+'&debug=0' +'&xp='+QQL+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+QQM+'&ref='+Ads_ref+'&opt=' +2 +'&cmd=win';QQkB[QQkB.length]='QQt=open(\''+QQp+'\',\''+QQCk+'\',\''+QQu+'\');';}for (var intI=0 ;intI<QQkB.length ;intI++)
{QQHk+=QQkB[intI];}QQHk+='}'+'</scr'+'ipt>';document.writeln(QQHk);}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000050-2)
var QQvE=[];var QQwE=[];var QQxE;function QQyE(QQQg,QQRg,QQSg,QQPe)
{if(typeof(QQQg)=='undefined')
return [];var QQl,QQk;var QQTg=[];var QQUg=QQQg.split('x');var QQVg=QQUg[0];var QQWg=QQRg-QQVg;var QQk=QQUg.length;QQwE[QQPe]=[];for(QQl=1;QQl<QQk;QQl++)
{QQBi=QQUg[QQl].split(':');if(QQSg&&(QQBi[2]==-1))
QQTg[QQBi[0]]=[QQBi[1],-1];QQBi[2]-=QQWg;if(QQBi[2]>0)
QQTg[QQBi[0]]=[QQBi[1],QQBi[2]];if (typeof(QQwE[QQPe])=='undefined')
QQwE[QQPe]=[];QQwE[QQPe][QQwE[QQPe].length]=QQBi[0];}return QQTg;}function QQzE(QQTg,QQRg,QQPe)
{var QQSc;var QQQg=QQRg;var QQl;if (typeof(QQwE[QQPe])!='undefined')
{for (var intI=0;intI<QQwE[QQPe].length;intI++)
{QQl=QQwE[QQPe][intI];if (typeof(QQTg[QQl])!='undefined')
{QQQg+='x'+QQl+':'+QQTg[QQl][0]+':'+QQTg[QQl][1];}}}return QQQg;}function QQaF(QQXg,QQYg)
{while(QQXg.length>800)
QQXg=QQXg.substr(0,QQXg.lastIndexOf('#',QQXg.length-2)+1);QQvE[QQYg]=QQXg;}function QQbF(QQYg,QQAb)
{var QQZg='111';var QQAh='@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`';var QQk=0;var QQYa='#'+QQAb+':';var QQXg=QQvE[QQYg];var QQBh='';var QQY=QQXg.indexOf(QQYa);var QQCh=new Date();var QQDh,QQEh,QQFh,QQGh,QQHe;var QQHh,QQIh,QQJh,QQKh;if(QQXg=='')
QQXg='#';if(QQY>-1)
{QQEh=QQXg.substr(QQY+QQYa.length,3+QQYg);if(QQY>0)
QQBh=QQXg.substr(0,QQY);QQDh=QQXg.length-QQY-QQYa.length-3-QQYg;if(QQDh>0)
QQBh+=QQXg.substr(QQY+QQYa.length+3+QQYg,QQDh);QQXg=QQBh;QQFh=new Date(QQAh.indexOf(QQEh.charAt(0))+2000,QQAh.indexOf(QQEh.charAt(1))-1,QQAh.indexOf(QQEh.charAt(2)));QQCh.setHours(0);QQCh.setMinutes(0);QQCh.setSeconds(0);QQGh=(QQCh.getTime()-QQFh.getTime())/1000/60/60/24;intAltWTag=(QQFh.getDay()==0?7:QQFh.getDay());intNeuWTag=(QQCh.getDay()==0?7:QQCh.getDay());intAltMTag=QQFh.getDate();intNeuMTag=QQCh.getDate();QQZg=((QQGh>0.1)?'1':'0')+(((QQGh>6)||(intAltWTag>intNeuWTag))?'1':'0')+((((QQGh>29)||(intAltMTag>intNeuMTag))&&(QQYg!=1&&QQYg!=14))?'1':'0');if(QQYg==1||QQYg==14)
QQk=QQAh.indexOf(QQEh.charAt(3));}QQEh='#'+QQAb+':';QQHe=QQCh.getYear();if(QQHe<1900)
QQHe+=1900;QQEh+=QQAh.charAt(QQHe-2000);QQEh+=QQAh.charAt(QQCh.getMonth()+1);QQEh+=QQAh.charAt(QQCh.getDate());if(QQYg==1||QQYg==14)
{QQk++;if(QQk>21)
QQk=21;QQEh+=QQAh.charAt(QQk);QQZg+=QQAh.charAt(QQk);}QQXg=QQEh+QQXg;QQaF(QQXg,QQYg);return QQZg;}function QQcF(QQYa,QQYg,QQLh)
{var QQQa,QQRa,QQDh,QQMh,QQNh;var QQXg=QQvE[QQYg];var QQBh='';var QQOh='';var QQPh=-1;if(QQXg=='')
QQXg='#';QQYa='#'+QQYa+'-';QQQa=QQXg.indexOf(QQYa);if(QQQa!=-1)
QQRa=QQXg.indexOf('#',QQQa+1);if((QQQa!=-1)&&(QQRa!=1))
{QQMh=QQXg.substring(QQQa+QQYa.length,QQRa);if(QQQa>0)
QQBh=QQXg.substr(0,QQQa);QQDh=QQXg.length-QQRa;if(QQDh>0)
QQBh+=QQXg.substr(QQRa,QQDh);QQXg=QQBh;if(QQYg==6)
{QQNh=QQMh.split('-');QQOh=QQNh[0];QQMh=QQNh[1];}QQPh=QQLh-parseInt(QQMh,10);if(QQPh>1200)
QQPh=-1;}QQvE[QQYg]=QQXg;return [QQPh,QQOh];}function QQdF(QQc)
{var QQQh=new Date();var QQPh=QQQh.getHours()*60*60+QQQh.getMinutes()*60+QQQh.getSeconds();var QQRh,QQSh;QQRh=QQcF(Ads_wid,6,QQPh);QQSh=QQcF(QQc,5,QQPh);var QQTh=(QQRh[0]==-1);var QQUh=(QQSh[0]==-1);var QQVh=(QQTh?'1':'0')+(QQUh?'1':'0');if(!QQTh)
QQVh+=QQmD(QQRh[0],4)+QQRh[1];QQaF('#'+Ads_wid+'-'+Ads_iid+'-'+QQPh+QQvE[6],6);QQaF('#'+QQc+'-'+QQPh+QQvE[5],5);return QQVh;}function QQeF()
{var QQUb=QQcD();var QQl,QQWh,QQSc,QQXh,QQYh,QQZh,QQAi,QQBi,QQYg;var QQCi,QQDi;var QQNa=document.cookie;var QQSg=(QQNa.toLowerCase().indexOf('sestest')>-1);document.cookie='SESTEST=1'+QQeD(-1);var QQEi=QQNa.split(';');var QQk=QQEi.length;var QQNc=new Date();QQxE=Math.round(QQNc.getTime()/1000/60);QQvE=['','',[],'','','','',[],[],[],QQdB,'',[],'',''];QQvE=QQfF('',QQEi,QQk,QQSg);if(Ads_uid!='')
{QQEi=Ads_userdata.split(';');QQk=QQEi.length;QQvE[2]=[];for(QQl=1;QQl<(QQk-1);QQl++)
{QQZh=QQEi[QQl].split(',');QQvE[2][QQZh[0]]=[QQZh[1],1];}}if(QQvE[3]=='1')
QQzA=true;}function QQfF(QQUb,QQEi,QQk,QQSg)
{var QQl;var QQvE;var QQSc;QQvE=['','',[],'','','','',[],[],[],QQdB,'',[],'',''];for(QQl=0;QQl<QQk;QQl++)
{QQYg=-1;QQZh=QQEi[QQl].split('=');QQSc=QQZh[0];QQYh=QQZh[1];if(QQSc.charAt(0)==' ')
QQSc=QQSc.substr(1,QQSc.length-1);if(QQSc.substr(0,QQUb.length)==QQUb)
QQXh=QQSc.substring(QQUb.length,QQSc.length);else
QQXh='';if(QQXh=='KIDYMD')
QQvE[1]=QQYh;else if(QQXh=='WIDYMD')
QQvE[0]=QQYh;else if(QQSc=='BSUID')
QQvE[3]=QQYh;else if(QQSc=='BNDLVL')
QQvE[10]=QQYh;else if(QQXh=='VISKAM')
QQvE[5]=QQYh;else if(QQXh=='VISWEB')
QQvE[6]=QQYh;else if(QQXh=='FRQSTR')
{if (QQYh.indexOf("|")!=-1)
QQZh=QQYh.split('|');else
QQZh=QQYh.split(',');QQvE[2]=QQyE(QQZh[0],QQxE,QQSg,2);QQvE[7]=QQyE(QQZh[1],QQxE,QQSg,7);QQvE[8]=QQyE(QQZh[2],QQxE,QQSg,8);QQvE[9]=QQyE(QQZh[3],QQxE,QQSg,9);QQvE[12]=QQyE(QQZh[4],QQxE,QQSg,12);}if(QQXh=='KIDCYMD')
QQvE[14]=QQYh;else if(QQXh=='WIDCYMD')
QQvE[13]=QQYh;}return QQvE;}function QQgF(QQc,QQNd)
{var QQFi,QQGi,QQCe,QQHi;var QQIi='';var QQUb=QQcD();var QQJi=KAS[QQNd][4][5];if(KAS[QQNd][4][4]>0)
QQIi=QQdD(QQJi);else if((KAS[QQNd][5]&1)>0)
{QQIi=QQdD(20);QQJi=20;}if(QQIi!='')
{QQCe=parseInt(QQiF(QQc,2)+1,10);if(Ads_uid!='')
{QQFi=Ads_userdata.split(';'+QQc+',');if(QQFi.length==2)
{QQGi=Ads_userdata.split(','+QQc+';');Ads_userdata=QQFi[0]+';'+QQGi[1];}Ads_userdata+=QQc+','+QQCe+','+QQJi+','+QQc+';';document.write('<img src="http://uboot.as-eu.falkag.net/usr?cmd=write&id='+Ads_uid+'&data='+Ads_userdata+'&rdm='+Math.random()+'" width="1" height="1">');}else
QQjF(QQc,2,QQCe,QQJi);}}function QQhF(QQc,QQNd,QQd,QQs,QQKi)
{var QQUb=QQcD();var QQy=[];var QQLi,QQNa;QQgF(QQc,QQNd);if(QQd>0)
{if(BAS[QQs][2][4]>0)
QQjF(QQd,9,QQiF(QQd,9)+1,BAS[QQs][2][5]);}if(((KAS[QQNd][4][22]&1)>0)&&(IAS[4]>0))
QQjF(Ads_wid,7,QQiF(Ads_wid,7)+1,IAS[5]);if(((KAS[QQNd][4][22]&2)>0)&&(IAS[6]>0))
QQjF(Ads_nid,8,QQiF(Ads_nid,8)+1,IAS[7]);if ((typeof(IAS[17])!='undefined')&&(typeof(QQaC[Ads_wid])!='undefined')&&(typeof(KAS[QQNd][13])!='undefined'))
{if(((KAS[QQNd][4][22]&4)>0)&&(KAS[QQNd][13]>0)&&(QQaC[Ads_wid].length>0)&&(typeof(QQaC[Ads_wid][KAS[QQNd][13]])!='undefined'))
{arrFamily=QQaC[Ads_wid][KAS[QQNd][13]];QQjF(arrFamily[0],12,QQiF(arrFamily[0],12)+1,arrFamily[2]);}}QQNa=QQzE(QQvE[2],QQxE,2)+'|' +QQzE(QQvE[7],QQxE,7)+'|' +QQzE(QQvE[8],QQxE,8)+'|' +QQzE(QQvE[9],QQxE,9)+'|' +QQzE(QQvE[12],QQxE,12);QQLi=QQbF(1,QQc);QQy[1]='&bls3='+QQLi.substr(0,3)+QQbF(0,Ads_wid)+QQLi.substr(3,1);QQy[1]+='&bls4='+QQdF(QQc);strClickAuswertung=QQbF(14,QQc);QQy[0]='&ucl='+strClickAuswertung.substr(0,3)+QQbF(13,Ads_wid)+strClickAuswertung.substr(3,1);if(QQzA)
QQy[1]+='&uid=1';QQoD(1,'SETTING TOP-LEVEL DOMAIN',QQNa);document.cookie='FRQSTR='+QQNa+QQeD(60*24*365);document.cookie='WIDYMD='+QQvE[0]+QQeD(60*24*30);document.cookie='KIDYMD='+QQvE[1]+QQeD(60*24*30);document.cookie='VISKAM='+QQvE[5]+QQeD(20);document.cookie='VISWEB='+QQvE[6]+QQeD(20);QQoD(1,'Cookie Auswertung [Click/Impression]',QQy[0]+'/'+QQy[1]);return QQy;}function QQiF(QQAb,QQPe)
{if(typeof(QQvE[QQPe][''+QQAb+''])!='undefined')
return parseInt(QQvE[QQPe][''+QQAb+''],10);else
return 0;}function QQjF(QQAb,QQPe,QQCe,QQJi)
{if(typeof(QQvE[QQPe][''+QQAb+''])!='undefined')
QQvE[QQPe][''+QQAb+''][0]=QQCe;else
{if (typeof(QQwE[QQPe])=='undefined')
QQwE[QQPe]=[];QQwE[QQPe][QQwE[QQPe].length]=QQAb;QQvE[QQPe][''+QQAb+'']=[QQCe,QQJi];}}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000050-2)
function QQwD(QQZc,QQAd)
{var QQl=0;var QQk=QQZc.length;if(QQk==0)
return -1;while((QQl<QQk-1)&&(QQAd>QQZc[QQl][1]))
{QQAd-=QQZc[QQl][1];QQl++;}return QQZc[QQl][0];}function QQxD(QQBd,QQCd,QQDd)
{var QQl,QQEd,QQFd,QQGd;if(QQBd>QQDd)
{QQEd=QQDd/QQBd;for(QQl=QQCd;QQl<QQlB.length;QQl++)
QQlB[QQl][1]*=QQEd;QQBd=QQDd;}QQDd-=QQBd;return QQDd;}function QQyD()
{var QQBb,QQHd,QQId,QQJd,QQKd;var QQLd=-2;var QQMd=KAS.length;var QQDd=100;var QQNd,QQc,QQGd,QQOd,QQPd,QQQd,QQRd,QQSd,QQTd;var QQBd=0;var QQCd;QQlB=[];for (QQNd=0;QQNd<QQMd;QQNd++)
{QQKd=((KAS[QQNd][5]&2)>0);if(KAS[QQNd][2]!=QQLd)
{if(QQLd!=-2)
QQDd=QQxD(QQBd,QQCd,QQDd);QQLd=KAS[QQNd][2];QQBd=0;QQCd=QQlB.length;}QQOd=KAS[QQNd][8];QQPd=KAS[QQNd][10];QQQd=IAS[10];if((QQQd-QQPd)>0)
QQOd=QQOd*QQQd/(QQQd-QQPd);QQGd=KAS[QQNd][1];if(QQOd<=0)
QQOd=QQGd;QQRd=(QQGd/QQOd-1)*2+1;var QQUd=QQR