//script generated by SiteXpert (www.xtreeme.com/sitexpert/)
//Copyright(C) 1998-2003 Xtreeme GmbH
NS60=(navigator.userAgent.indexOf("Netscape6/6.0")!=-1)
Opera=(navigator.userAgent.indexOf('Opera')!=-1)||(navigator.appName.indexOf('Opera')!=-1)||(window.opera)
Opera7=(Opera&&document.createElement!=null&&document.addEventListener!=null)
IE4=(document.all&&!Opera)
mac=((IE4)&&(navigator.appVersion.indexOf("Mac")!=-1))
DOM=document.documentElement&&!IE4&&!Opera
NS4=navigator.appName.indexOf("Netscape")>-1&&!DOM
mswnd=(navigator.appVersion.indexOf("Windows")!=-1||navigator.appVersion.indexOf("WinNT")!=-1)
if(IE4){
av=navigator.appVersion
avi=av.indexOf("MSIE")
if(avi==-1){version=parseInt(av);}else{version=parseInt(av.substr(avi+4));}}
var ver='2.0.2'
var m1=new Object
m1.name='m1'
m1.fnm='index_m1'
if(!window.lastm||window.lastm<1)lastm=1
if(NS4||IE4||DOM||Opera){
m1.v17=null
m1.v17Timeout=''
var maxZ=1000
m1.v18
m1.targetFrame
var docLoaded=false
m1.bIncBorder=true
m1.v29=null
m1.v29Str=''
m1.scrollDelay=50
m1.scrollStep=10
m1.showDelayedTimeout=null
m1.fadingSteps=8
m1.v21="/js"
m1.maxlev=2
m1.v22=0
m1.bVarWidth=0
m1.bShowDel=0
m1.v23=200
m1.levelOffset=20
m1.bord=1
m1.vertSpace=2
m1.sep=1
m1.v19=false
m1.bkv=0
m1.rev=0
m1.shs=0
m1.xOff=0
m1.yOff=0
m1.v20=false
m1.cntFrame=""
m1.menuFrame=""
m1.v24=""
m1.mout=true
m1.iconSize=8
m1.closeDelay=400
m1.tlmOrigBg="#F2F5FF"
m1.tlmOrigCol="#34538C"
m1.v25=false
m1.v52=false
m1.popupOpacity=0
m1.v11=false
m1.rm=-1
m1.v10=0
m1.popupLeftPad=5
m1.v01=2
m1.tlmHlBg="#6C83BC"
m1.tlmHlCol="White"
m1.borderCol="#C9D9FF"
m1.menuHorizontal=true
m1.scrollHeight=6}
m1.lev0=new Array("10px",false,false,"#34538C","#EAF0FF","White","Verdana,Arial,Helvetica","#6C83BC")
m1.lev1=new Array("10px",false,false,"#34538C","#EAF0FF","White","Verdana,Arial,Helvetica","#6C83BC")
m1.lev2=new Array("10px",false,false,"#34538C","#EAF0FF","White","Verdana,Arial,Helvetica","#6C83BC")
window.m1templFold="<td width=\"160\" onmouseover=\"chgBg(m1,'m1tlm(menuind)',3);exM(m1,'m1mn(foldind)','m1tlm(menuind)',event)\"\nonmouseout=\"chgBg(m1,'m1tlm(menuind)',0);coM(m1,'m1mn(foldind)')\"  id=\"m1tlm(menuind)\"  class=\"m1mit\" \n bgcolor=\"#F2F5FF\">\n<a id=\"m1tlm(menuind)a\" class=\"m1CL0\" href=\"(menuurl)\" target=\"(trgframe)\" onMouseOver=\"exMNS(m1,'m1mn(foldind)',event)\"\nonmouseout=\"coMNS(m1,'m1mn(foldind)')\" >\n<div id='m1mn(foldind)top' class='topFold'>(menutxt)<img width=\"8\" height=\"8\" src=\"/js/index_m1iad.gif\" align=\"texttop\" border=\"0\" /></div></a></td>\n"
window.m1templFile="<td width=\"160\" onmouseover=\"chgBg(m1,'m1tlm(menuind)',3);exM(m1,'none','',event)\"\nonmouseout=\"chgBg(m1,'m1tlm(menuind)',0,1)\"  id=\"m1tlm(menuind)\"  class=\"m1mit\" \n bgcolor=\"#F2F5FF\">\n<a id=\"m1tlm(menuind)a\" class=\"m1CL0\" href=\"(menuurl)\" target=\"(trgframe)\">\n<div class='topFold'>(menutxt)</div></a></td>\n"
window.m1templSep=""
window.m1tbl1="<table  id=\"m1mainSXMenu1\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" bgcolor=\"#C9D9FF\" ><tr><td><table  id=\"m1mainSXMenu2\" cellspacing=\"1\" cellpadding=\"2\" class=\"x1\" border=\"0\" width=\"100%\" >\n<tr align=\"left\">\n"
window.m1tbl2="</tr></table></td></tr></table>\n"
m1mn=new Array()
function gpc(ar){
var i
var cnt=0
for(i=0;i<ar.length/3;i++){
if(ar [i*3+2]==1){
cnt++}}
return cnt}
function insertItemToMenu(itemText,itemUrl,parentMenu,bPopup,nMenu){
var parentMenuId=parentMenu ? parentMenu :((nMenu ? nMenu : 'm1')+'mn')
var arr=eval('window.'+parentMenuId)
if(!arr){
eval('window.'+parentMenuId+'= new Array ();')
arr=eval('window.'+parentMenuId)}
var item=parentMenu ?(arr.length/3+1):(gpc(arr)+1)
if(arr.push)arr.push(itemText,itemUrl,bPopup ? 1 : 0)
else{
arr [arr.length]=itemText
arr [arr.length]=itemUrl
arr [arr.length]=bPopup?1:0}
return(parentMenuId+(parentMenu ? '_' : '')+item.toString())}
function addSubMenu(itemText,itemUrl,parentMenu,nMenu){
return insertItemToMenu(itemText,itemUrl,parentMenu,1,nMenu)}
function addMenuItem(itemText,itemUrl,parentMenu,nMenu){
return insertItemToMenu(itemText,itemUrl,parentMenu,0,nMenu)}
function addTopLevelMenu(itemText,itemUrl,nMenu){
var url
if(!itemUrl || itemUrl==''){
url='javascript:void(0);'}
else{
url=itemUrl}
return addSubMenu(itemText,url,null,nMenu)}
function getTopLevelMenu(nSubMenu,nMenu){
return((nMenu ? nMenu : 'm1')+'mn'+nSubMenu)}
absPath=""
if(m1.v19&&!m1.v20){
if(window.location.href.lastIndexOf("\\")>window.location.href.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
absPath=window.location.href.substring(0,window.location.href.lastIndexOf(sepCh)+1)}
m1.popupOffset=0
m1.v02=m1.v23
if(Opera&&!Opera7)document.write("<"+"script language='JavaScript1.2' src='/js/menu_opera.js'><"+"/"+"script>")
else if(NS4)document.write("<"+"script language='JavaScript1.2' src='/js/menu_ns4.js'><"+"/"+"script>")
else if(document.getElementById)document.write("<"+"script language='JavaScript1.2' src='/js/menu_dom.js'><"+"/"+"script>")
else document.write("<"+"script language='JavaScript1.2' src='/js/menu_ie4.js'><"+"/"+"script>")
document.write("<style type='text/css'>\n")
document.write(".m1CL0,.m1CL0:link{text-decoration:none;width:100%;color:#34538C; }\n")
document.write(".m1CL0:visited{color:#34538C}\n")
document.write(".topFold{position:"+(!DOM&&!IE4?"relative":"static")+"}\n")
if(NS4&&!m1.v25)document.write(".x1{padding-left:5px;padding-right:45px;}\n")
document.write(".m1mit{"+((!NS4||m1.v25)?"padding-left:5px;padding-right:45px;":"")+"color:#34538C; font-family:Verdana,Helvetica; font-size:11px; }\n")
document.write("</style>\n\n")
