var __txt = new Array()
__txt[0]=["Recent Windows Software:","<a href=\"http://www.softpedia.com/get/System/Launchers-Shutdown-Tools/MSConfig-Cleanup.shtml\" target=\"_blank\">MSConfig Cleanup 1.30</a><br/><a href=\"http://www.softpedia.com/get/Others/Home-Education/Test-Maker.shtml\" target=\"_blank\">Test Maker 1.2</a><br/><a href=\"http://www.softpedia.com/get/Internet/Servers/WEB-Servers/Okapiland-Explorer.shtml\" target=\"_blank\">Okapiland Explorer 2.0</a><br/><a href=\"http://www.softpedia.com/get/Internet/News-Newsgroups-Blog-Tools/NZB-leecher.shtml\" target=\"_blank\">NZB leecher 1.3.10</a><br/><a href=\"http://www.softpedia.com/get/Programming/File-Editors/EngInSite-Perl-Editor-Lite.shtml\" target=\"_blank\">EngInSite Perl Editor Lite 2.0...</a><br/><a href=\"http://www.softpedia.com/get/Security/Keylogger-Monitoring/SoftPerfect-Network-Protocol-Analyzer.shtml\" target=\"_blank\">SoftPerfect Network Protocol A...</a><br/><a href=\"http://www.softpedia.com/get/Office-tools/Other-Office-Tools/Examine.shtml\" target=\"_blank\">Examine32 4.30</a><br/><a href=\"http://www.softpedia.com/get/Others/Finances-Business/PaintCOST-Estimator-for-Excel.shtml\" target=\"_blank\">PaintCOST Estimator for Excel ...</a><br/><a href=\"http://www.softpedia.com/get/Network-Tools/Network-Information/Network-Inventory-Monitor.shtml\" target=\"_blank\">Network Inventory Monitor 3.3...</a><br/><a href=\"http://www.softpedia.com/get/Science-CAD/VistaMetrix.shtml\" target=\"_blank\">VistaMetrix 1.30</a><br/>"]
__txt[1]=["Recent Games:","<a href=\"http://games.softpedia.com/get/Shareware-Games/3D-TetColor.shtml\" target=\"_blank\">3D TetColor 1.1</a><br/><a href=\"http://games.softpedia.com/get/Shareware-Games/QuadroNoid-II.shtml\" target=\"_blank\">QuadroNoid II 1.0</a><br/><a href=\"http://games.softpedia.com/get/Shareware-Games/BrickBuster.shtml\" target=\"_blank\">BrickBuster 1.23</a><br/><a href=\"http://games.softpedia.com/get/Shareware-Games/SolSuite-Solitaire-Card-Games-Suite.shtml\" target=\"_blank\">SolSuite 2005 - Solitaire Card...</a><br/><a href=\"http://games.softpedia.com/get/Shareware-Games/Breaker-of-blocks.shtml\" target=\"_blank\">Breaker of blocks 1.1</a><br/><a href=\"http://games.softpedia.com/get/Shareware-Games/PacBomber.shtml\" target=\"_blank\">PacBomber 1.7.2</a><br/><a href=\"http://games.softpedia.com/get/Shareware-Games/3D-technical-drawing-puzzle.shtml\" target=\"_blank\">3D technical drawing puzzle 3....</a><br/><a href=\"http://games.softpedia.com/get/Shareware-Games/The-Goalkeeper.shtml\" target=\"_blank\">The Goalkeeper 1.1.8</a><br/><a href=\"http://games.softpedia.com/get/Shareware-Games/Circulate.shtml\" target=\"_blank\">Circulate 1.06</a><br/><a href=\"http://games.softpedia.com/get/Shareware-Games/Cosmodeluxe-3D.shtml\" target=\"_blank\">Cosmodeluxe 3D 1.2.4</a><br/>"]
__txt[2]=["Recent Drivers:","<a href=\"http://drivers.softpedia.com/get/Other-DRIVERS-TOOLS/Others/Via-K8N800-K8M800-16944006-WHQL.shtml\" target=\"_blank\">Via K8N800/K8M800 16.94.40.06 ...</a><br/><a href=\"http://drivers.softpedia.com/get/BIOS/ENMIC/ENMIC-8TX2-plus-Bios-18.shtml\" target=\"_blank\">ENMIC 8TX2+ Bios 1.8</a><br/><a href=\"http://drivers.softpedia.com/get/BIOS/ENMIC/ENMIC-3VX-plus-Bios-107a.shtml\" target=\"_blank\">ENMIC 3VX+ Bios 1.07a</a><br/><a href=\"http://drivers.softpedia.com/get/BIOS/ENMIC/ENMIC-3VAXE-Bios-103a.shtml\" target=\"_blank\">ENMIC 3VAXE Bios 1.03a</a><br/><a href=\"http://drivers.softpedia.com/get/BIOS/ENMIC/ENMIC-8TTX3-Bios-121.shtml\" target=\"_blank\">ENMIC 8TTX3 Bios 1.21</a><br/><a href=\"http://drivers.softpedia.com/get/BIOS/Gigabyte/GIGABYTE-GA7VM-333MRZ-Bios-104.shtml\" target=\"_blank\">GIGABYTE GA7VM-333M-RZ Bios 1....</a><br/><a href=\"http://drivers.softpedia.com/get/BIOS/Gigabyte/Gigabyte-8IG1000MF-Bios-106F.shtml\" target=\"_blank\">Gigabyte 8IG1000MF Bios 1.06F...</a><br/><a href=\"http://drivers.softpedia.com/get/BIOS/Gigabyte/Gigabyte-GA-7VM400AM-Bios-106f.shtml\" target=\"_blank\">Gigabyte GA-7VM400AM Bios 1.06...</a><br/><a href=\"http://drivers.softpedia.com/get/BIOS/Gigabyte/GIGABYTE-GA7VM333MRZ-Bios-14.shtml\" target=\"_blank\">GIGABYTE GA7VM333M-RZ Bios 1.4...</a><br/><a href=\"http://drivers.softpedia.com/get/BIOS/J-Mark/J-Mark-J-401A-Bios-102.shtml\" target=\"_blank\">J-Mark J-401A Bios 1.02</a><br/>"]
__txt[3]=["Recent MAC Software:","<a href=\"http://mac.softpedia.com/get/Audio/Audio-Toolbox.shtml\" target=\"_blank\">Audio Toolbox 1.7.0</a><br/><a href=\"http://mac.softpedia.com/get/Utilities/Envelope-Window.shtml\" target=\"_blank\">Envelope Window 2.0b2</a><br/><a href=\"http://mac.softpedia.com/get/Utilities/AppleOff.shtml\" target=\"_blank\">AppleOff 1.01</a><br/><a href=\"http://mac.softpedia.com/get/Audio/Numerology.shtml\" target=\"_blank\">Numerology 1.4.2t</a><br/><a href=\"http://mac.softpedia.com/get/Internet-Utilities/FireFoxy.shtml\" target=\"_blank\">FireFoxy 1.4.3</a><br/><a href=\"http://mac.softpedia.com/get/Utilities/Chromatic-Tuner.shtml\" target=\"_blank\">Chromatic Tuner 1.1.3</a><br/><a href=\"http://mac.softpedia.com/get/Dashboard-Widgets/News/OnlyNewYork-RSS-Widget.shtml\" target=\"_blank\">OnlyNewYork RSS Widget 2.0</a><br/><a href=\"http://mac.softpedia.com/get/Dashboard-Widgets/Games-Widgets/SuperBrain-Widget.shtml\" target=\"_blank\">SuperBrain Widget 1.0</a><br/><a href=\"http://mac.softpedia.com/get/DTP-Prepress/PicMark.shtml\" target=\"_blank\">PicMark 1.2</a><br/><a href=\"http://mac.softpedia.com/get/Audio/Strobe-Tuner.shtml\" target=\"_blank\">Strobe Tuner 1.0.3</a><br/>"]
__txt[4]=["Recent Mobile Phones:","<a href=\"http://mobile.softpedia.com/phones/LG/LG-M4410.shtml\" target=\"_blank\">LG M4410</a><br/><a href=\"http://mobile.softpedia.com/phones/LG/LG-M4330.shtml\" target=\"_blank\">LG M4330</a><br/><a href=\"http://mobile.softpedia.com/phones/LG/LG-F2410.shtml\" target=\"_blank\">LG F2410</a><br/><a href=\"http://mobile.softpedia.com/phones/Motorola/Motorola-E895.shtml\" target=\"_blank\">Motorola E895</a><br/><a href=\"http://mobile.softpedia.com/phones/Samsung/Samsung-D550.shtml\" target=\"_blank\">Samsung D550</a><br/><a href=\"http://mobile.softpedia.com/phones/Nokia/Nokia-6280.shtml\" target=\"_blank\">Nokia 6280</a><br/><a href=\"http://mobile.softpedia.com/phones/Nokia/Nokia-6270.shtml\" target=\"_blank\">Nokia 6270</a><br/><a href=\"http://mobile.softpedia.com/phones/Nokia/Nokia-6111.shtml\" target=\"_blank\">Nokia 6111</a><br/><a href=\"http://mobile.softpedia.com/phones/Nokia/Nokia-6060.shtml\" target=\"_blank\">Nokia 6060</a><br/><a href=\"http://mobile.softpedia.com/phones/Sony-Ericsson/Sony-Ericsson-S600.shtml\" target=\"_blank\">Sony-Ericsson S600</a><br/>"]
__txt[5]=["Recent News:","<a href=\"http://news.softpedia.com/news/Pete-Doherty-Dumped-By-Kate-Moss-5343.shtml\" target=\"_blank\">Pete Doherty Dumped By Kate Mo...</a><br/><a href=\"http://news.softpedia.com/news/Kylie-Minogue-Undergoes-Aggressive-Anti-Cancer-Chemotherapy-5341.shtml\" target=\"_blank\"> Kylie Minogue Undergoes Aggre...</a><br/><a href=\"http://news.softpedia.com/news/A-New-Comedy-Set-In-The-White-House-5340.shtml\" target=\"_blank\">A New Comedy Set In The White ...</a><br/><a href=\"http://news.softpedia.com/news/Westlife-Shane-Filan-Has-A-Babygirl-5339.shtml\" target=\"_blank\">Westlife Shane Filan Has A Bab...</a><br/><a href=\"http://news.softpedia.com/news/New-Line-Cinema-to-adapt-Mark-Burnell-s-thriller-The-Rhythm-Section-for-the-big-screen-5336.shtml\" target=\"_blank\">New Line Cinema To Adapt Mark ...</a><br/><a href=\"http://news.softpedia.com/news/Beyonce-Plans-A-Long-2006-Vacation-5335.shtml\" target=\"_blank\">Beyonce Plans A Long 2006 Vaca...</a><br/><a href=\"http://news.softpedia.com/news/Nicole-Kidman-Takes-Her-Kids-To-An-Exclusive-Tennis-Camp-5334.shtml\" target=\"_blank\">Nicole Kidman Takes Her Kids T...</a><br/><a href=\"http://news.softpedia.com/news/Vince-Vaughn-moves-to-Chicago-5332.shtml\" target=\"_blank\">Vince Vaughn Moves To Chicago...</a><br/><a href=\"http://news.softpedia.com/news/Tom-Hanks-To-Star-In-Ant-Bully-5333.shtml\" target=\"_blank\">Tom Hanks To Star In &quot;Ant...</a><br/><a href=\"http://news.softpedia.com/news/Jude-Law-Didn-t-Get-Sienna-Miller-Back-Yet-5330.shtml\" target=\"_blank\">Jude Law Didn&#039;t Get Sienn...</a><br/>"]
__txt[6]=["Stiri Recente:", "<a href=\"http://news.softpedia.com/news/ICANN-a-aprobat-domeniul-tel-ro-5329.shtml\" target=\"_blank\">ICANN a aprobat domeniul .tel...</a><br/><a href=\"http://news.softpedia.com/news/Noi-DVD-playere-mobile-din-seria-PET-de-la-Philips-ro-5328.shtml\" target=\"_blank\">Noi DVD-playere mobile din ser...</a><br/><a href=\"http://news.softpedia.com/news/Skype-se-vede-si-pe-telefoanele-video-ro-5326.shtml\" target=\"_blank\">Skype se vede si pe telefoanel...</a><br/><a href=\"http://news.softpedia.com/news/HP-isi-trimite-angajatii-in-concediu-fara-plata-permanent-ro-5325.shtml\" target=\"_blank\">HP isi trimite angajatii in co...</a><br/><a href=\"http://news.softpedia.com/news/Johnny-Depp-de-la-ciocolata-la-striptease-ro-5313.shtml\" target=\"_blank\">Johnny Depp de la ciocolata la...</a><br/><a href=\"http://news.softpedia.com/news/Regizorul-David-Lynch-isi-lanseaza-o-fundatie-destinata-meditatiei-transcedentale-ro-5314.shtml\" target=\"_blank\">Regizorul David Lynch isi lans...</a><br/><a href=\"http://news.softpedia.com/news/Cu-Morandi-in-Europa-ro-5315.shtml\" target=\"_blank\">Cu Morandi in Europa</a><br/><a href=\"http://news.softpedia.com/news/Colin-Farrel-cel-mai-dorit-burlac-din-America-ro-5305.shtml\" target=\"_blank\">Colin Farrell, cel mai dorit b...</a><br/><a href=\"http://news.softpedia.com/news/Apocalypto-noul-film-regizat-de-Mel-Gibson-ro-5306.shtml\" target=\"_blank\">&quot;Apocalypto&quot;, noul f...</a><br/><a href=\"http://news.softpedia.com/news/Angelina-Jolie-i-a-salvat-viata-fiicei-sale-ro-5304.shtml\" target=\"_blank\">Angelina Jolie i-a salvat viat...</a><br/>"]

var __stl = new Array()
__stl[0]=["white","#E63333","#C93737","#F1F5FF"]
__stl[1]=["white","#B93766","#C73A6E","#F1F5FF"]
__stl[2]=["white","#D26E16","#C8712A","#F1F5FF"]
__stl[3]=["white","#509737","#479A48","#F1F5FF"]
__stl[4]=["white","#3772C4","#3873C5","#F1F5FF"]
__stl[5]=["white","#5B52A8","#6256BC","#F1F5FF"]
__stl[6]=["white","#5B52A8","#6256BC","#F1F5FF"]

function lepop(idx){
return overlib(__txt[idx][1], WIDTH, 210, STICKY, MOUSEOFF, DELAY, 200, FGCOLOR, __stl[idx][3], BGCOLOR, __stl[idx][2], TEXTCOLOR, __stl[idx][1], CAPTION, __txt[idx][0], CAPCOLOR, "#FFFFFF", CLOSETEXT, "X", CLOSEFONTCLASS, "cl_font_class", TEXTFONTCLASS, "celltext", BORDER, 1);
}

function validate(elem){
if((elem.value != undefined) && (elem.value != "")) return true;
else return false;
}

function bmark_msg(){
var isie = 0;

//if(navigator.appVersion.indexOf("MSIE") != -1)

if(window.external) isie = 1;

if(isie == 1){
window.external.AddFavorite(location.href, document.title); return false;
}
else{
alert("Your web-browser does not support automatic addition of favourites/bookmarks.\n\n"+
"You will have to use a key-combination or menu option specific to your browser:\n"+
"  - in Mozilla/Mozilla Firefox try: Ctrl-D\n"+
"  - in Opera try Ctrl-T\n"+
"  - for other browsers consult the program's help system/documentation\n\n\n"+
"NOTE: The key combinations above will bookmark the page you were browsing at that moment.");
}
}